### ISSUE TITLE
[Crash] on startup - a lot of mods are present 1.18.2

### ISSUE THREAD

**Issue by xR4YM0ND** [apace100/autotag#1]
[latest.log](https://gist.github.com/SpigotDE/d50354054d0058e3bc6a78812f099175)

**Comment by apace100** [comment]
Hi, thanks for the report. Would you mind trying it with this version of the mod instead? (You need to unzip the file to get the JAR, as you can't upload JAR files to comments here it seems).
[AutoTag-1.18.2-1.0.1-alpha.1.zip](https://github.com/apace100/autotag/files/8583915/AutoTag-1.18.2-1.0.1-alpha.1.zip)

**Comment by xR4YM0ND** [comment]
Doesnt crash <3

here is the [latest.log](https://gist.github.com/SpigotDE/64d26e2417eb9be7d4e34eda7180ace3) if you are interested

**Comment by apace100** [comment]
Awesome, I'll push this update then. Thanks for testing.
