### ISSUE TITLE
Tag Suggestions

### ISSUE THREAD

**Issue by Globox1997** [apace100/autotag#2]
Hello hello,
I was thinking about new tags and few came to my mind, which should get discussed a little.
Some mods, especially weapon themed mods, add new types of shields, bows, crossbows and tridents which all belong to the weapon category. In the mod Tiered I use at least the shield tag to provide easier compat to mods which add new shields to mc. 
Do you think it makes sense to add tags for those weapon types and maybe even a "weapons" tag (would be the counterpart to the armor tag)?

**Comment by apace100** [comment]
Good ideas! What do you think would be appropriate conditions for these?
Do you think a simple `instanceof` would suffice for these (i.e. with `ShieldItem`, `BowItem`, `CrossbowItem` and `TridentItem`)?

**Comment by Globox1997** [comment]
For BowItem, CrossbowItem and TridentItem instanceof is appropiate since for example MCDW items depend on the first two in their respective class.
The ShieldItem has a downside. The most official lib I found for new shield items is [Fabric-Shield-Lib](https://github.com/CrimsonDawn45/Basic-Shields-Fabric).
It provides a [FabricShieldItem](https://github.com/CrimsonDawn45/Fabric-Shield-Lib/blob/main/src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java) class which doesn't extend the ShieldItem class but implements a new implemented interface called FabricShield. 
Not sure if autotag should support/add compatibility with it.

**Comment by apace100** [comment]
Sounds good. Thanks for the info about the shield library. Since that's the one I heard of before as well, and it seems to be that it's even mentioned in the "Shields" tutorial on the Fabric wiki, I'd add an integration for that mod.
Question: Would you include shields in the general weapons tag, or not? Would you include them in the tools tag?
I'm also thinking of adding a tag for "ranged weapons" (bows, crossbows, trident) and "melee weapons" (swords and trident). Let me know what you think about those.

**Comment by Globox1997** [comment]
Sounds good!
In rl I would say shields count to the weapon category but in the view of vanilla code I would say, since it can't do damage, it doesn't fit in there. I wouldn't include it in the tools tag either but don't have a good reason for it, it just doesn't feel right to put it in there. 
I haven't had a use case yet for those new tags but they might be useful in the future or for others.
Just thought about a new entity tag but vanilla has already good ones. [Impact Projectiles](https://minecraft.fandom.com/wiki/Tag#entity_types_impact_projectiles)
