### ISSUE TITLE
Update Tag List For New Version

### ISSUE THREAD

**Issue by ghost** [apace100/autotag#9]
I noticed that there were tags that were present in the latest version that were not present [here](https://github.com/apace100/autotag/blob/1.18/README.md#list-of-tags). Perhaps more specifically, the tag `c:shears` was what alerted me to this.

**Comment by apace100** [comment]
`c:shears` is not added or populated by AutoTag, it's part of Fabric API's convention tags module:
https://github.com/FabricMC/fabric/blob/1.20.1/fabric-convention-tags-v1/src/generated/resources/data/c/tags/items/shears.json
